---
title: "The Demise of Local Journalism and Democratic Health in Canada"
author: 
  - Jet McCullough
  - William Chan
thanks: "Code and data are available at: [https://github.com/jethroid/INF2167-Proposal-Group-2](https://github.com/jethroid/INF2167-Proposal-Group-2)."
date: August 1, 2026
date-format: long
format: pdf
number-sections: true
bibliography: paper_references.bib
---

# Abstract

# Introduction

Local journalism in Canada is experiencing a sharp decline, with 2.5 million Canadians, or 7 percent of the population, living in postal codes with one or no local media outlets [@macdonald_news_2025]. As local news provides important information about community affairs to electorates, the continued loss of local news can leave citizens less informed about local issues, potentially discouraging political participation and thereby threatening the democratic system. Despite these crucial political implications, existing studies on local news deserts have overwhelmingly focused on the United States, which has a different electoral system and political culture from Canada. Therefore, our project aims to contribute to the understanding of the relationship between local news and political participation among Canadians by answering the following research question:

**How does the net trajectory of the local news market affect a riding’s voter turnout relative to the national baseline?**

Our hypothesis is that ridings that experience more negative changes in their local news market will have lower voter turnout than the national average. To answer this question, we will use federal election results from Elections Canada and local news outlet data from the Local News Research Project, led by researchers at Toronto Metropolitan University [@lindgren_local_nodate] to conduct a linear regression analysis quantifying the relationship between changes in the local news and voter turnout in Canada. We found that \[add findings…\]

# Relevant Literature

The loss of local news in Canada affects a sizable portion of the population, but its effects are not distributed equally. @barber_left_2026 found that news outlet closures are more likely to occur in “left-behind” places, places that are “small, shrinking, peripheral", reflecting the broader inequalities driven by globalization. Economic decline in these places has resulted in unemployment, business closures, and retrenchment in public services, all of which have likely undermined the vitality of local news outlets (p. 11). @barber_left_2026 also highlighted the political consequences of news closures in left-behind places, arguing that voter turnout is likely to decline because of a lack of access to information and pessimism that their votes do not matter in elections. Additionally, the loss of local news can widen the space for misinformation and conspiracy theories, contributing to greater support for populist and polarizing agendas (p. 12).

@hayes_decline_2018 argue that local news helps electorates develop the political knowledge necessary to participate in the democratic process, such as voting. Using U.S. House campaigns in 2010 and 2014, they showed that citizen engagement declined as coverage of House races declined. With less reporting on candidates and their campaigns, fewer voters were able to rate the candidates in a survey (p. 335). The authors argue that the deterioration of political knowledge is concerning, as an informed electorate that is able to hold elected officials accountable improves the representation and legitimacy of the political system.

Besides being a source of information, local journalism can serve as an active venue for community members to participate in the political process. @magasic_examining_2023 provide examples from Australian towns where residents expressed their opinions and advocated for social issues, such as cuts to welfare services. Local journalists help maintain the relationship between the government and the public, allowing for the exchange of information through sections such as “Letters to the Editor.” Local news fosters a sense of community and thereby promotes civic engagement.

@haddock_local_2026 expanded on this idea by arguing that the loss of local news negatively affects community social capital, resulting in a feedback loop that weakens trust between voters and institutions. Reduced coverage of local issues and elected officials affects the community’s ability to monitor crime and intensifies polarization in rural communities, as residents turn to national, partisan media for political information.

# Dataset and Methods
We rely on datasets from three sources. The local news dataset was downloaded from the Local News Research Project, which releases its local news map report as .xlsx files on a bi-monthly basis, tracking changes in local news outlets in Canada since 2008 [@lindgren_local_nodate]. For our analysis, we obtained the data as of June 8, 2026, which contains 1,337 news outlets and 18 variables. It is a spatial dataset because it includes the coordinates of individual outlets, which are crucial for our subsequent step of merging the data with the election results. Transition Type is another key variable that records changes to news outlets and groups them into eight categories: “closed,” “shifted to online,” “closed due to merger,” “decrease in service,” “new,” “increase in service,” “new outlet produced by merger,” and “daily becomes a community paper.” The Date of Change column is used to map each change to the corresponding election period.

The second dataset we use consists of Canadian federal election results for 2015, 2019, and 2021, downloaded from Elections Canada [@electionscanada]. The agency publishes election results by polling station for each election year as CSV files stored in a compressed folder. Total Votes and Electors are the key variables used to calculate voter turnout. Each CSV file also includes the Electoral District Number, which identifies the riding and is used to merge the election results with the local news dataset.

The Federal Electoral District Boundary Files are the third dataset we use to merge the local news and election datasets [@fed_boundaries]. We downloaded the boundary file for the 2021 census year, which applies to all three elections in our study. The file is in shapefile (.shp) format and contains geometric attributes for polygons delineating the boundaries of federal electoral districts. In addition to spatial attributes, the file includes metadata for each riding, particularly the FEDDGUID_CEFIDUGD column, which refers to the Dissemination Geography Unique Identifier for electoral districts [@fed_boundaries_dict]. The last five digits of this column correspond to the Electoral District Number in the election data and are therefore used for merging.

To merge the local news and election datasets, we first merge the news data with the boundary file by conducting a spatial join using the Simple Features (sf) package [@simple_features]. Each observation in the news dataset is assigned an electoral district ID from the shapefile if it falls within the corresponding polygon. With the electoral district ID attached, the news dataset can then be merged with the election results using a left join.



$$turnout\_diff_{it} = \beta_0 + \beta_1 \cdot cumulative\_news_{it} + \epsilon_{it}$$

# Results and Findings

# Discussion and Conclusion

\newpage

# References
